// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/labstack/echo/v4"
	"github.com/vuduongtp/go-core/config"
	"github.com/vuduongtp/go-core/internal/api/auth"
	"github.com/vuduongtp/go-core/internal/api/country"
	user2 "github.com/vuduongtp/go-core/internal/api/user"
	"github.com/vuduongtp/go-core/internal/db/user"
	"github.com/vuduongtp/go-core/internal/model"
	"github.com/vuduongtp/go-core/internal/util/db"
	"github.com/vuduongtp/go-core/pkg/server"
	"github.com/vuduongtp/go-core/pkg/server/middleware/jwt"
	"github.com/vuduongtp/go-core/pkg/util/crypter"
	dbutil2 "github.com/vuduongtp/go-core/pkg/util/db"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApplication uses wire to build all dependencies
func InitializeApplication() (*Application, error) {
	configuration, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	db, err := ProvideDB(configuration)
	if err != nil {
		return nil, err
	}
	echo := ProvideServer(configuration)
	service := ProvideJWT(configuration)
	auth := ProvideAuth(service)
	userDB := ProvideUserDB()
	jwt := ProvideAuthJWT(service)
	crypterService := ProvideCrypter()
	authService := ProvideAuthService(db, userDB, jwt, crypterService)
	userService := ProvideUserService(db, userDB, crypterService)
	dbutilDB := ProvideCountryDB()
	countryService := ProvideCountryService(db, dbutilDB)
	application := &Application{
		Config:     configuration,
		DB:         db,
		Server:     echo,
		JWT:        service,
		Auth:       auth,
		AuthSvc:    authService,
		UserSvc:    userService,
		CountrySvc: countryService,
	}
	return application, nil
}

// wire.go:

// ProvideConfig loads configuration
func ProvideConfig() (*config.Configuration, error) {
	return config.Load()
}

// ProvideDB initializes database connection
func ProvideDB(cfg *config.Configuration) (*gorm.DB, error) {
	return dbutil.New(cfg.DbType, cfg.DbDsn, cfg.DbLog)
}

// ProvideUserDB creates user database repository
func ProvideUserDB() *user.DB {
	return user.NewDB()
}

// ProvideCountryDB creates country database repository
func ProvideCountryDB() *dbutil2.DB {
	return country.NewDB()
}

// ProvideCrypter creates crypter service
func ProvideCrypter() *crypter.Service {
	return crypter.New()
}

// ProvideJWT creates JWT service
func ProvideJWT(cfg *config.Configuration) *jwt.Service {
	return jwt.New(cfg.JwtAlgorithm, cfg.JwtSecret, cfg.JwtDuration)
}

// ProvideAuth creates Auth interface from JWT service
func ProvideAuth(jwtSvc *jwt.Service) model.Auth {
	return jwtSvc
}

// ProvideAuthJWT creates auth.JWT interface from JWT service
func ProvideAuthJWT(jwtSvc *jwt.Service) auth.JWT {
	return jwtSvc
}

// ProvideAuthService creates auth service
func ProvideAuthService(db *gorm.DB, userDB *user.DB, jwtSvc auth.JWT, crypterSvc *crypter.Service) auth.Service {
	return auth.New(db, userDB, jwtSvc, crypterSvc)
}

// ProvideUserService creates user service
func ProvideUserService(db *gorm.DB, userDB *user.DB, crypterSvc *crypter.Service) user2.Service {
	return user2.New(db, userDB, crypterSvc)
}

// ProvideCountryService creates country service
func ProvideCountryService(db *gorm.DB, countryDB *dbutil2.DB) country.Service {
	return country.New(db, countryDB)
}

// ProvideServer creates Echo server
func ProvideServer(cfg *config.Configuration) *echo.Echo {
	return server.New(&server.Config{
		Stage:        cfg.Stage,
		Port:         cfg.Port,
		ReadTimeout:  cfg.ReadTimeout,
		WriteTimeout: cfg.WriteTimeout,
		AllowOrigins: cfg.AllowOrigins,
		Debug:        cfg.Debug,
	})
}

// Application holds all initialized services
type Application struct {
	Config     *config.Configuration
	DB         *gorm.DB
	Server     *echo.Echo
	JWT        *jwt.Service
	Auth       model.Auth
	AuthSvc    auth.Service
	UserSvc    user2.Service
	CountrySvc country.Service
}
