// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/kevinxvu/goone/config"
	"github.com/kevinxvu/goone/internal/api/service/auth"
	"github.com/kevinxvu/goone/internal/api/service/country"
	"github.com/kevinxvu/goone/internal/api/service/user"
	"github.com/kevinxvu/goone/internal/model"
	"github.com/kevinxvu/goone/internal/repository"
	"github.com/kevinxvu/goone/pkg/database"
	"github.com/kevinxvu/goone/pkg/openai"
	"github.com/kevinxvu/goone/pkg/server"
	"github.com/kevinxvu/goone/pkg/server/middleware/jwt"
	"github.com/labstack/echo/v4"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApplication uses wire to build all dependencies
func InitializeApplication() (*Application, error) {
	configuration, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	db, err := ProvideDB(configuration)
	if err != nil {
		return nil, err
	}
	echo := ProvideServer(configuration)
	service := ProvideJWT(configuration)
	auth := ProvideAuth(service)
	userRepository := ProvideUserDB()
	jwt := ProvideAuthJWT(service)
	authService := ProvideAuthService(db, userRepository, jwt)
	userService := ProvideUserService(db, userRepository)
	countryRepository := ProvideCountryDB()
	countryService := ProvideCountryService(db, countryRepository)
	openaiService := ProvideOpenAIService(configuration)
	application := &Application{
		Config:     configuration,
		DB:         db,
		Server:     echo,
		JWT:        service,
		Auth:       auth,
		AuthSvc:    authService,
		UserSvc:    userService,
		CountrySvc: countryService,
		OpenAI:     openaiService,
	}
	return application, nil
}

// wire.go:

// ProvideConfig loads configuration
func ProvideConfig() (*config.Configuration, error) {
	return config.Load()
}

// ProvideDB initializes database connection
func ProvideDB(cfg *config.Configuration) (*gorm.DB, error) {
	return database.New(cfg.DbType, cfg.DbDsn, cfg.DbLog)
}

// ProvideUserDB creates user database repository
func ProvideUserDB() *repository.UserRepository {
	return repository.NewUserRepository()
}

// ProvideCountryDB creates country database repository
func ProvideCountryDB() *repository.CountryRepository {
	return repository.NewCountryRepository()
}

// ProvideJWT creates JWT service
func ProvideJWT(cfg *config.Configuration) *jwt.Service {
	return jwt.New(cfg.JwtAlgorithm, cfg.JwtSecret, cfg.JwtDuration)
}

// ProvideAuth creates Auth interface from JWT service
func ProvideAuth(jwtSvc *jwt.Service) model.Auth {
	return jwtSvc
}

// ProvideAuthJWT creates auth.JWT interface from JWT service
func ProvideAuthJWT(jwtSvc *jwt.Service) auth.JWT {
	return jwtSvc
}

// ProvideAuthService creates auth service
func ProvideAuthService(db *gorm.DB, userDB *repository.UserRepository, jwtSvc auth.JWT) auth.Service {
	return auth.New(db, userDB, jwtSvc)
}

// ProvideUserService creates user service
func ProvideUserService(db *gorm.DB, userDB *repository.UserRepository) user.Service {
	return user.New(db, userDB)
}

// ProvideCountryService creates country service
func ProvideCountryService(db *gorm.DB, countryDB *repository.CountryRepository) country.Service {
	return country.New(db, countryDB)
}

// ProvideServer creates Echo server
func ProvideServer(cfg *config.Configuration) *echo.Echo {
	return server.New(&server.Config{
		Stage:        cfg.Stage,
		Port:         cfg.Port,
		ReadTimeout:  cfg.ReadTimeout,
		WriteTimeout: cfg.WriteTimeout,
		AllowOrigins: cfg.AllowOrigins,
		Debug:        cfg.Debug,
	})
}

// ProvideOpenAIService creates OpenAI service
func ProvideOpenAIService(cfg *config.Configuration) *openai.Service {
	return openai.New(openai.Config{
		APIKey:     cfg.OpenAIAPIKey,
		BaseURL:    cfg.OpenAIBaseURL,
		Timeout:    cfg.OpenAITimeout,
		MaxRetries: cfg.OpenAIMaxRetries,
		TextModel:  cfg.OpenAITextModel,
		AudioModel: cfg.OpenAIAudioModel,
	})
}

// Application holds all initialized services
type Application struct {
	Config     *config.Configuration
	DB         *gorm.DB
	Server     *echo.Echo
	JWT        *jwt.Service
	Auth       model.Auth
	AuthSvc    auth.Service
	UserSvc    user.Service
	CountrySvc country.Service
	OpenAI     *openai.Service
}
